CREATE TABLE `tags` (`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,`name` CHAR(127) NOT NULL,PRIMARY KEY (`id`),UNIQUE INDEX `name` (`name`)) COLLATE='latin1_swedish_ci' ENGINE=MyISAM AUTO_INCREMENT=1;

